import react from 'react'
import { ReactDOM } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import header from './componets/menu/header.module.css'
import Menu from './componets/menu/Menu'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mundo Criativo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Menu>{["home", "blog", "tecnologias", "Ciencias", "Newsletter"]}</Menu>
      <main>

      </main>
    </>
  )
}
